# The URL the site will be built for
base_url = "https://luciengheerbrant.com"

# The site title and description; used in feeds by default.
title = "Lucien Gheerbrant"

# The default language; used in feeds.
default_language = "en"

# The site theme to use.
theme = "duckquill"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = false

# The taxonomies to be rendered for the site and their configuration of the default languages
# Example:
#     taxonomies = [
#       {name = "tags", feed = true}, # each tag will have its own feed
#       {name = "tags"}, # you can have taxonomies with the same name in multiple languages
#       {name = "categories", paginate_by = 5},  # 5 items per page for a term
#       {name = "authors"}, # Basic definition: no feed or pagination
#     ]
#
taxonomies = [
  {name = "tags", feed = true},
]

# The filename to use for the feed. Used as the template filename, too.
# Defaults to "atom.xml", which has a built-in template that renders an Atom 1.0 feed.
# There is also a built-in template "rss.xml" that renders an RSS 2.0 feed.
feed_filename = "atom.xml"

# When set to "true", a feed is automatically generated.
generate_feed = false

author = "Lucien GHEERBRANT"

[markdown]
# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = true

# The theme to use for code highlighting.
# See below for list of allowed values.
highlight_theme = "css"
highlight_themes_css = [
  { theme = "solarized-dark", filename = "syntax-theme-dark.css" },
  { theme = "solarized-light", filename = "syntax-theme-light.css" },
]

# Whether smart punctuation is enabled (changing quotes, dashes, dots in their typographic form)
# For example, `...` into `…`, `"quote"` into `“curly”` etc
smart_punctuation = true

[languages.fr]
title = "Le site de Lucien Gheerbrant"

[extra]
# Sets browser theme color,
# see https://developer.mozilla.org/en-US/docs/Web/HTML/Element/meta/name/theme-color
primary_color = "#DC8ADD"
primary_color_alpha = "rgba(222, 144, 223, 0.2)"

# If the favicon is GIF or not
animated_favicon = false

# Tera date format (not used in comments!),
# see https://docs.rs/chrono/0.4.31/chrono/format/strftime/index.html
# for all available variables.
date_format = "%A %e %B %Y"

# URL to issue tracker
issues_url = ""
# URL to website's source code
source_url = "https://github.com/lusinge/site-pro"
# Additional stylesheets; expects it to be in the ./static/ directory.
# If you are using Sass it will be compiled there anyway.
# stylesheets = [
#   "YOUR_STYLE.css",
#   "ALSO_YOUR_STYLE.css"
# ]

stylesheets = [
  "custom.css"
]


[extra.nav]
# Display Atom/RSS feed button in the nav
show_feed = true
# Whether to use icons in the nav
icons = true
# Links used in the nav; any icon from https://icons.getbootstrap.com
# can be used as the icon. The bi- prefix should not be added.
links = [
  {url = "$BASE_URL/profile/resume", name = "📄 Resume"},
# {url = "$BASE_URL/profile/cover-letter", name = "📝 Cover Letter"},
  {url = "mailto:lucien.gheerbrant@etu.emse.fr", name = "📧 E-mail"},
  {url = "https://linkedin.com/in/lucien-gheerbrant", name = "🖇️ LinkedIn"},
]

[extra.footer]
# URL to the website without the https:// part, used for Johnvertisement leaderboard
johnvert_ref = "luciengheerbrant.com"
# "© Title, YEAR" in the footer
show_copyright = true
# Johnvertisement in the footer
show_johnvert = false
# "Powered by Zola and Duckquill" in footer
show_powered_by = true
# Link to website source
show_source = true

# Based on https://github.com/cassidyjames/cassidyjames.github.io/blob/75cd2a202de7a1026de1ea00a4ef1d5b2675c7ff/_config.yaml#L35-L74
#
# Mastodon-powered commenting.
# Values can be overridden in front-matter, e.g.
# for multi-author blogs or guest posts.
#
# These variables are also used for Mastodon verification,
# the needed rel="me" link is set in the head based on these.
[extra.comments]
# Your Mastodon API host; this should be where you have an account
host = "mastodon.online"
# Used to determine who the original/verified poster is;
# role may be expanded in the future (e.g. for moderation).
user = "lcnghr"
# Optional; required to fetch more than 60 replies to any given blog post.
# Application access token with read:statuses scope; NOTE: IF INCLUDED, ANYONE
# WILL BE ABLE TO READ THE ASSOCIATED ACCOUNT'S PRIVATE STATUSES. It is highly
# recommended to use a dedicated bot/API account to create an application with
# scope read:statuses.
#token = "jTNX9pAV8XEPBby0cPWF6CmGY60kkIy4vidggfxXmoQ"
