on:
  push:
    branches:
      - main
      - dev
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build and deploy to gh-pages
        if: github.ref == 'refs/heads/main'
        uses: shalzz/zola-deploy-action@master
        env:
          PAGES_BRANCH: gh-pages
          TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and deploy to gh-pages-dev
        if: github.ref == 'refs/heads/dev'
        uses: shalzz/zola-deploy-action@master
        env:
          PAGES_BRANCH: gh-pages-dev
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
